language: C

os: linux
dist: xenial

script:
- mkdir -p build
- cd build
- cmake ..
- make
- make test

after_success:
- cd ..
- cd scripts
- chmod +x auto_merge.sh
- "./auto_merge.sh"

env:
  global:
    secure: IpaFobwiDpHQiYSXYqB6r15XQ3d43zIvNj69GwbAanaSq/vlEj9y2nYv/cruHTVIsIeTM2on3kHPzBmPlz00luCM83ddeg/ZDMwlE/mb5EHPl4+bRnoFiDXcfSrlt0J2RklgQHMl36+zWCiUqaZksFtqJ9EBdX2Cvjo+IUVr6m/Wyw4VRoDg4ToE8QqVkhiU0HwYGKzskq8XmwYRDZsH/IAaY8cGPd27Ybtrq2Ee8rVmD/gOJtinvu9JhdepXtNzvR38PMOBftTtAs7s13TsIfEGBXtS50lMaRqqzrh85CM8QKtvQyvsdEqiFRe8etENm/2nI6h5/hJjGz55skT3WkcZrBL+UWDmbdP8U02GABZ1fedHkoI3DgeShvHtnbRBCZ40/0yzTer4qLOYAosMnxskcFeCECFo4/YPp2DPajWdkQqTGkfrDNSpFoc2FVfmxOtO4hwHG7BGv7T8Mo+0pw2pxIleRD2p398lwSgZh1lzPpObtwAvjKRMsdvnadn8SxYHrZjXNgO09WpG9oFaFTR4rYO9pQGJ8BGXUNo8O8PSz/qpGvZicNkOa+qVg5cyZmRpU2v4pEtqLBYC6lmnchMWcODWqJxmflLS3qgpDzNbAcyQKvAw3ILgbmaZARlr5g//4927BZg1+gJ5nt6wWY6ZEf5WhN6nYl+uZPDGzBA=

