language: C
os: linux
dist: xenial
script:
- mkdir -p build
- cd build
- cmake ..
- make
- make test
after_success:
- cd ..
- cd scripts
- chmod +x auto_merge.sh
- "./auto_merge.sh"

env:
  global:
    secure: b2/XwqBcXqXFWBdpJmJqFIGx9G10BLORUi6qKjELx2no2AHJT3ItktHZgsxIgK9hgrWxm3YegQI2KD3G+ew0EVRPFll2fUW+M2AMi27IwR9BRCqrA4XQajTVY16ZgTpz0DfMxaAY29P+fPLwTyOqG1wvJxatHNxMFTIXOVxpeP0U1uOkeQHlQU53oVzWw9PuIqMNmkv+vPCCP7vDzmyTwmFJoYix94svFd2vxxPQfD68cIbzGpsIbdKedpEwrE972D5AsqPhU7gDWcHSIGSsWSVOlKd++caSnOfp6Rzr3VTdOlna/zNORNXZ3Y/ekE3QHPlsCM2CLVGII9+0n8ytRueAyMMJ60u0SelzMaCWEQzz76g2HHecP8+pn9vnWr9lJLAaE0NKr0h2139O183ulVjuRzQ0iw12hFuEmGNCEBBpOf7HfPIHNc3QqR8fs137BI6uEonLMIGJpswdtth8uZA92QCHAEq9dCyS8wHA6c0Qk6F9NQzh40DQLQ26FygqrMTLLXjvOCuMR4Mr0sWlLzhJ+AC5VR3QMqd/Y3+9m1x3F/YXqO+y7Nzm2tlwldG3+V6nGJ1MNnkNSppJPSzyyxVne2cpjFj6wprCWTPHGIgKyVC/NofLsa8ivC1r3E5CXC4eiE7X3Fj9r/yt+ArTfIZc/2U+h9N8WZtU76MUi7Q=
